FROM ros:noetic-ros-base


ENV DIRPATH /root/
WORKDIR $DIRPATH

# To avoid tzdata asking for geographic location...
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y ros-noetic-image-geometry ros-noetic-pcl-ros \
    ros-noetic-cv-bridge git cmake build-essential unzip pkg-config autoconf \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    gdb \
    libopencv-dev \
    libopencv-contrib-dev \
    libeigen3-dev \
    # Use libvtk5-dev, libgtk2.0-dev in ubuntu 16.04 \
    libvtk7-dev libgtk-3-dev \
    libatlas-base-dev gfortran \
    libparmetis-dev \
    python3-wstool python3-catkin-tools \
    # libtbb recommended for speed: \
    libtbb-dev 

# Build catkin workspace
RUN apt-get install -y ros-noetic-image-pipeline ros-noetic-geometry ros-noetic-rviz


RUN echo 'source /opt/ros/noetic/setup.bash' >> ~/.bashrc
RUN echo 'source ${HOME}/catkin_ws/devel/setup.bash' >> ~/.bashrc




# RUN git clone https://github.com/MIT-SPARK/Kimera-VIO-ROS.git /catkin_ws/src/Kimera-VIO-ROS
# RUN cd /catkin_ws/src/Kimera-VIO-ROS 
#     # && git checkout ___
# RUN cd /${HOME}/catkin_ws/src/ && wstool init && \
#     wstool merge Kimera-VIO-ROS/install/kimera_vio_ros_https.rosinstall && wstool update

# RUN cd /catkin_ws/src/gtsam && git checkout tags/4.2 && \
#     cd /catkin_ws/src


# RUN . /opt/ros/noetic/setup.sh && cd /catkin_ws && \
#     catkin init && \
#     catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release \
#     -DGTSAM_USE_SYSTEM_EIGEN=ON \
#     -DGTSAM_USE_SYSTEM_METIS=ON \
#     -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF \
#     -DGTSAM_BUILD_TESTS=OFF \
#     -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF \
#     -DGTSAM_BUILD_UNSTABLE=ON \
#     -DGTSAM_ROT3_EXPMAP=ON \
#     -DGTSAM_TANGENT_PREINTEGRATION=OFF && \
#     catkin build -j8

